version: '3'
services:
    jupyter:
        image: darlon/dask:1.0
        volumes:
            - ./data:/data
        ports:
            - "8889:8888"
            - "8887:8787"
        command: ["sh", "-c", "jupyter-notebook --allow-root --ip '0.0.0.0' --no-browser --NotebookApp.token='' --NotebookApp.password=''"]
    scheduler:
        image: darlon/dask:1.0
        volumes:
            - ./data:/data
        ports:
            - "8787:8787"
        command: ["dask-scheduler"]
    worker:
        image: darlon/dask:1.0
        volumes:
            - ./data:/data
        command: ["dask-worker", "tcp://scheduler:8786"]
        depends_on:
            - "scheduler"
        deploy:
            resources:
                limits:
                    memory: 4g
